title: Hello, world! I'm Harendra Singh
description: > # this means to ignore newlines until "baseurl:"
  This Website is about Harendra Singh. You can find his blog and portfolio here !
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://harendrasingh.tech" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: Harendra Singh # add your name
author-img: harendra-singh.jpg # add your photo
about-author: I am a Android and Web Developer. Currently in love with Machine Learning ! # add description
twitter: # add your Twitter handle
facebook: harendrasinghhs98# add your Facebook handle
github: harendrasingh22 # add your Github handle
linkedin: harendrasingh98 # add your Linkedin handle
email: mail@harendrasingh.tech # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
